name: Schedule Test Runs

on:
  schedule:
    # Modify this to specify when the job should run. The below is daily at 12 AM GMT
    - cron: '0 0 * * *'
  # Allows the workflow to be run manually through the GitHub UI
  workflow_dispatch:

jobs:
  schedule_tests:
    strategy:
      matrix:
        sf_org_alias: [INTEGRATION, UAT]

    env:
        ENVIRONMENT: ${{ matrix.sf_org_alias }}

    runs-on: ubuntu-latest

    steps:

    - run: echo what is the secret ${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }}

    - name: Checkout code
      uses: actions/checkout@v4

    - name: Install Salesforce CLI
      run: |
        wget https://developer.salesforce.com/media/salesforce-cli/sfdx/channels/stable/sfdx-linux-x64.tar.xz
        mkdir ~/sfdx
        tar xJf sfdx-linux-x64.tar.xz -C ~/sfdx --strip-components 1
        echo "$HOME/sfdx/bin" >> $GITHUB_PATH
        ~/sfdx/bin/sfdx version

    - name: Populate auth file with SFDX_URL secret
      run: echo ${{ secrets[format('SFDX_{0}_URL', env.ENVIRONMENT)] }} > ./SFDX_${{ matrix.sf_org_alias }}_URL.txt

    - name: Authenticate to Org
      run: sfdx auth:sfdxurl:store -f ./SFDX_${{ matrix.sf_org_alias }}_URL.txt -s -a ${{ matrix.sf_org_alias }}

    - name: Run all tests and store test run Id
      run: |
        sfdx apex run test --test-level RunLocalTests --result-format human > ./id.txt
        echo "$(node ./extractId.js)" > ${{ matrix.sf_org_alias }}_test_run_id.txt

    - name: Upload the test run Id as an artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ matrix.sf_org_alias }}_test_run_id
        path: ${{ matrix.sf_org_alias }}_test_run_id.txt
